#!/usr/bin/env python

# check_rabbitmq_queue
#
# Copyright (c) <2017>, <Andrei Buzoianu>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Use the output of rabbitmqctl list_queues to read number of ready/unacknowledged messages in a specific queue

# Author: Andrei Buzoianu <andrei@buzoianu.info>
# 2017-03-23 Version 0.1

import sys
from distutils.spawn import find_executable
from os import getuid
from re import sub
from re import match
from subprocess import check_output
from optparse import OptionParser

def main ():
    # Nagios status codes
    STATE_OK = 0
    STATE_WARNING = 1
    STATE_CRITICAL = 2
    STATE_UNKNOWN = 3

    parser = OptionParser(usage="usage: %prog -w limit -c limit", version="%prog 0.1")
    parser.add_option("-r", "--ready", action="store_true", dest="ready", help="get number of ready messages (I'm hunting wabbits)")
    parser.add_option("-u", "--unacked", action="store_true", dest="unacked", help="get number of unacknowledged messages")
    parser.add_option("-p", "--vhost", dest="vhost", metavar="STRING", type="string")
    parser.add_option("-q", "--queue", dest="queue", metavar="STRING", type="string")
    parser.add_option("-w", "--warning", dest="warn", metavar="INT", type="int")
    parser.add_option("-c", "--critical", dest="crit", metavar="INT", type="int")
    (options, args) = parser.parse_args()

    if len(sys.argv[1:]) != 9:
        parser.print_help()
        sys.exit(STATE_UNKNOWN)

    CRIT = int(options.crit)
    WARN = int(options.warn)

    if CRIT > WARN:
        sys.stdout.write("Status : FAIL - Critical value can't be greater than warning value\n")
        sys.exit(STATE_UNKNOWN)

    # construct rabbitmqctl command
    check_command = ['/usr/sbin/rabbitmqctl', '-q', 'list_queues', 'name']

    if options.ready:
        messages = 'ready'
        check_command.append('messages_ready')

    if options.unacked:
        messages = 'unacknowledged'
        check_command.append('messages_unacknowledged')

    # match given vhost    
    check_command.append('-p')
    check_command.append(options.vhost)

    # If non-root run with sudo
    if getuid() != 0:
        check_command.insert(0, find_executable('sudo'))

    try:
        queues = check_output(check_command)
    except Exception as exc:
        sys.stdout.write("Status : FAIL\n")
        sys.exit(STATE_UNKNOWN)

    queues = queues.splitlines()

    for queue in queues:
	if match(r'^kraken', queue):
            values = queue.split("\t")

            if values[1] <= CRIT:
                sys.stdout.write("RabbitMQ CRITICAL - %s %s messages \n" % (values[1], messages))
                sys.exit(STATE_CRITICAL)
            if values[1] <= WARN:
                sys.stdout.write("RabbitMQ WARNING - %s %s messages \n" % (values[1], messages))
                sys.exit(STATE_WARNING)

            sys.stdout.write("RabbitMQ OK - %s %s messages\n" % (values[1], messages))
            sys.exit(STATE_OK)

if __name__ == '__main__':
    main()
